# Site settings
title: Grayscale
email: aguilapedro@gmail.com
url: https://pedroaguilar.github.io
description: "What I do with my free time."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Pedro Aguilar's website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pedrozoso
  - title: facebook
    url: https://www.facebook.com/aguilapedro
  - title: quora
    url: https://www.quora.com/profile/Pedro-Aguilar
  - title: github
    url: https://github.com/aguilapedro

# Build settings
markdown: kramdown
permalink: pretty
